title: Recommended Products Blog
description: Reviews and recommendations for the best products available
baseurl: "/Recommended-Products-Blog" # the subpath of your site, typically /repository-name
url: "https://USERNAME.github.io" # Replace USERNAME with your GitHub username

# Build settings
markdown: kramdown
permalink: pretty

# Collections
collections:
  products:
    output: true
    permalink: /products/:path/

# Theme settings - using a minimal theme compatible with GitHub Pages
theme: minima

# Default layouts
defaults:
  - scope:
      path: ""
      type: "products"
    values:
      layout: "product"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

# Amazon affiliate ID (replace with your actual ID)
amazon_affiliate_id: YOUR-AFFILIATE-ID

# Exclude files from processing
exclude:
  - add_product.rb
  - process_urls.sh
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor/

# eBay store information
ebay_store: Goodandclean.shop
ebay_partner_id: 5338889850

# Collections
collections:
  leatherman:
    output: true
    permalink: /leatherman/:path/

# Default front matter
defaults:
  - 
    scope:
      path: ""
      type: "leatherman"
    values:
      layout: "leatherman" 