title: Good&Clean.shop
description: Reviews and recommendations for the best products available
baseurl: "/goodandclean.shop" # the subpath of your site, typically /repository-name
url: "https://jfeldstein.github.io" # Replace USERNAME with your GitHub username

# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge

# GitHub Pages settings
github: [metadata]
encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
future: true
jailed: false
gfm_quirks: paragraph_end

# Collections
collections:
  products:
    output: true
    permalink: /products/:path/
  leatherman:
    output: true
    permalink: /leatherman/:path/
  posts:
    output: true
    permalink: /posts/:path/

# Theme settings - using a minimal theme compatible with GitHub Pages
theme: minima

# Default layouts
defaults:
  - scope:
      path: ""
      type: "products"
    values:
      layout: "product"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "leatherman"
    values:
      layout: "leatherman"

# Amazon affiliate ID (replace with your actual ID)
amazon_affiliate_id: goodandclean-20

# eBay store information
ebay_store: Goodandclean.shop
ebay_partner_id: 5338889850

# Exclude files from processing
exclude:
  - add_product.rb
  - process_urls.sh
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor/
  - github-pages-setup.md 