title: Amazon Affiliate Product Recommendations
email: your-email@example.com
description: >-
  A collection of my favorite Amazon products with honest reviews and recommendations.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: your-github-username

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Amazon affiliate ID
amazon_affiliate_id: your-amazon-affiliate-id

# Collections
collections:
  products:
    output: true
    permalink: /products/:path/

# Default front matter
defaults:
  - 
    scope:
      path: ""
      type: "products"
    values:
      layout: "product"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
    values:
      layout: "default" 