title: Amazon Affiliate Product Recommendations
email: jfeldstein@gmail.com
description: >-
  A collection of my favorite Amazon products with honest reviews and recommendations.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: jfeldstein

# Build settings
markdown: kramdown
# theme: minima  # Commented out to use our custom theme
plugins:
  - jekyll-feed

# Amazon affiliate ID
amazon_affiliate_id: goodandclean-20

# eBay store information
ebay_store: Goodandclean.shop

# Collections
collections:
  products:
    output: true
    permalink: /products/:path/
  leatherman:
    output: true
    permalink: /leatherman/:path/

# Default front matter
defaults:
  - 
    scope:
      path: ""
      type: "products"
    values:
      layout: "product"
  -
    scope:
      path: ""
      type: "leatherman"
    values:
      layout: "leatherman"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
    values:
      layout: "default" 