name: Check Amazon Links

on:
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:
    # Allow manual triggering for testing

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Install dependencies
        run: |
          gem install httparty
          gem install mailgun-ruby

      - name: Check Amazon links
        run: ruby scripts/check_amazon_links.rb
        env:
          MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}
          MAILGUN_DOMAIN: ${{ secrets.MAILGUN_DOMAIN }}

      - name: Set up Email Notifications for Workflow Failures
        if: failure()
        run: |
          curl -s --user "api:$MAILGUN_API_KEY" \
            https://api.mailgun.net/v3/$MAILGUN_DOMAIN/messages \
            -F from="Good&Clean Link Checker <postmaster@jfeldstein.mailgun.org>" \
            -F to="jfeldstein@gmail.com" \
            -F subject="Amazon Link Check Failed - Good&Clean.shop" \
            -F html="<h1>Link Checker Workflow Failed</h1><p>The Amazon link check workflow failed to run.</p><p>Please check the GitHub Actions logs for more details: <a href='https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}'>Workflow run</a></p>"
        env:
          MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}
          MAILGUN_DOMAIN: ${{ secrets.MAILGUN_DOMAIN }} 