name: Update eBay Listings
permissions:
  contents: write

on:
  schedule:
    # Run every hour
    - cron: '0 * * * *'
  # Allow manual triggering
  workflow_dispatch:

jobs:
  update-listings:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true
        
    - name: Install dependencies
      run: bundle install
      
    - name: Run eBay scraper
      run: |
        # Create log directory if it doesn't exist
        mkdir -p logs
        
        # Run the scraper script
        echo "=== Updating Leatherman listings at $(date) ===" >> logs/update_log.txt
        bundle exec ruby scrape_ebay_listings.rb >> logs/update_log.txt 2>&1
        echo "Update completed at $(date)" >> logs/update_log.txt
        echo "=======================================" >> logs/update_log.txt
      
    - name: Check for changes
      id: check_changes
      run: |
        git status --porcelain
        echo "has_changes=$(git status --porcelain | wc -l | xargs)" >> $GITHUB_OUTPUT
      
    - name: Commit and push if there are changes
      if: steps.check_changes.outputs.has_changes != '0'
      run: |
        # Configure Git
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        
        # Add changes
        git add _leatherman/ assets/images/leatherman/ logs/update_log.txt
        
        # Commit with timestamp
        git commit -m "Auto-update eBay listings - $(date)"
        
        # Push changes
        git push 