name: Update eBay Listings
permissions:
  contents: write

on:
  schedule:
    # Run every hour
    - cron: '0 * * * *'
  # Allow manual triggering
  workflow_dispatch:

jobs:
  update-listings:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
        bundler-cache: true
        
    - name: Install dependencies
      run: bundle install
      
    - name: Run eBay scraper
      run: |
        # Create log directory if it doesn't exist
        mkdir -p logs
        
        # Run the scraper script
        echo "=== Updating Leatherman listings at $(date) ===" >> logs/update_log.txt
        bundle exec ruby scrape_ebay_listings.rb >> logs/update_log.txt 2>&1
        echo "Update completed at $(date)" >> logs/update_log.txt
        echo "=======================================" >> logs/update_log.txt
      
    - name: Check for product changes
      id: check_changes
      run: |
        # Check specifically for changes in product files, not logs
        CHANGES=$(git status --porcelain _leatherman/ assets/images/leatherman/ | wc -l | xargs)
        echo "Product changes detected: $CHANGES"
        echo "has_changes=$CHANGES" >> $GITHUB_OUTPUT
        
        # Extract the actual changes count from the script output
        ACTUAL_CHANGES=$(grep -A 1 "Update summary:" logs/update_log.txt | tail -1 | grep -o "[0-9]\+ total changes" | grep -o "[0-9]\+")
        if [ -z "$ACTUAL_CHANGES" ]; then
          ACTUAL_CHANGES=0
        fi
        echo "Actual product changes: $ACTUAL_CHANGES"
        echo "actual_changes=$ACTUAL_CHANGES" >> $GITHUB_OUTPUT
      
    - name: Commit and push if there are actual changes
      if: steps.check_changes.outputs.actual_changes != '0'
      run: |
        # Configure Git
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        
        # Add only product-related changes, not logs
        git add _leatherman/ assets/images/leatherman/
        
        # Get the actual changes count
        ACTUAL_CHANGES="${{ steps.check_changes.outputs.actual_changes }}"
        
        # Commit with timestamp and actual changes count
        git commit -m "Auto-update eBay listings with $ACTUAL_CHANGES changes - $(date)"
        
        # Push changes
        git push 